const $ = (id) => document.getElementById(id);
const api = () => ($('apiBase').value || '/api/v1').replace(/\/$/, '');
const show = (id, value) => { $(id).textContent = typeof value === 'string' ? value : JSON.stringify(value, null, 2); };
async function request(path, options = {}) { const response = await fetch(`${api()}${path}`, {headers:{'Content-Type':'application/json'}, ...options}); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || body.message || `${response.status}`); return body; }
function fail(id, error) { show(id, `失败：${error.message}`); $('status').textContent = '请求失败'; }
$('configBtn').onclick = async () => { try { show('configOutput', await request('/performance/config')); $('status').textContent = '配置读取成功'; } catch(e) { fail('configOutput',e); } };
$('poolBtn').onclick = async () => { try { show('poolOutput', await request('/performance/db-pool')); } catch(e) { fail('poolOutput',e); } };
$('tokenBtn').onclick = async () => { try { show('tokenOutput', await request('/performance/token-estimate',{method:'POST',body:JSON.stringify({text:$('tokenText').value})})); } catch(e) { fail('tokenOutput',e); } };
$('cacheBtn').onclick = async () => { try { show('cacheOutput', await request('/performance/cache',{method:'POST',body:JSON.stringify({key:$('cacheKey').value,value:$('cacheValue').value})})); } catch(e) { fail('cacheOutput',e); } };
$('embeddingBtn').onclick = async () => { try { show('embeddingOutput', await request('/performance/embedding-batch',{method:'POST',body:JSON.stringify({texts:$('embeddingText').value.split('\n').filter(Boolean)})})); } catch(e) { fail('embeddingOutput',e); } };
$('streamBtn').onclick = async () => { const output=$('streamOutput'); output.textContent='连接中…'; try { const response=await fetch(`${api()}/performance/stream`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('streamText').value})}); if(!response.ok) throw new Error(`HTTP ${response.status}`); const reader=response.body.getReader(); const decoder=new TextDecoder(); let buffer=''; output.textContent=''; while(true){const {value,done}=await reader.read(); if(done) break; buffer+=decoder.decode(value,{stream:true}); const events=buffer.split('\n\n'); buffer=events.pop(); for(const event of events){const line=event.split('\n').find(x=>x.startsWith('data:')); if(line){try{const data=JSON.parse(line.slice(5)); if(data.content) output.textContent+=data.content; if(data.message) output.textContent+=`\n错误：${data.message}`;}catch{}}}} } catch(e){output.textContent=`失败：${e.message}`;} };
