"""add document task state fields

Revision ID: 6ae9368fa90b
Revises: baa5fa38c0ad
Create Date: 2026-08-23 16:08:44.094650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae9368fa90b'
down_revision: Union[str, Sequence[str], None] = 'baa5fa38c0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'completed_at')
    op.drop_column('documents', 'processing_started_at')
    op.drop_column('documents', 'retry_count')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'task_id')
    # ### end Alembic commands ###
