"""add knowledge bases

Revision ID: baa5fa38c0ad
Revises: 270ae2a6b1ca
Create Date: 2026-08-23 14:30:24.113205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa5fa38c0ad'
down_revision: Union[str, Sequence[str], None] = '270ae2a6b1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('knowledge_base_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_documents_knowledge_base_id'), 'documents', ['knowledge_base_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_knowledge_base_id'), table_name='documents')
    op.drop_column('documents', 'knowledge_base_id')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
