"""add conversation summary checkpoint

Revision ID: e78a72b98e23
Revises: 837b87773985
Create Date: 2026-08-23 21:49:56.966799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78a72b98e23'
down_revision: Union[str, Sequence[str], None] = '837b87773985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary_message_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'messages', ['summary_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'summary_message_id')
    # ### end Alembic commands ###
